---
title: "ESM 206 Assignment 5"
author: "Zoe Duerksen-Salm & Audrey Nolan"
date: "11/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

```{r}
# attach packages
library(tidyverse)
library(janitor)
library(plotly)
library(kableExtra)
library(dplyr)
library(here)
library(ggbeeswarm)
library(car)

# read in data
mack_raw <- read_csv("mack_creek_vertebrates.csv") %>% 
  clean_names() %>% 
  select(-pitnumber, -length2, -notes)
```

Part A: 
```{r}
# notes from part A: 
# Pacific Giant Salamanders, Dicamptodon tenebrosus.(DITE)
# need to find total annual DTE counts

# wrangling data to get counts for OG and CC

counts_dite <- mack_raw %>% 
  filter(species == "DITE") %>% 
  group_by(year, species, section) %>%
  summarize(counts = sum(entity))

# make a graph showing counts
ggplot(counts_dite, aes(x = year, y = counts, group = section, color = section))+
  geom_line()+
  theme_minimal()

# orrrr.
ggplot(counts_dite, aes(x = year, y = counts))+
  geom_col()+
  facet_wrap(~section)
```

- Make graph showing counts

---

Part B: 
```{r}
# I = riffle, IP = Isolated pools, 
dite_2017 <- mack_raw %>%
  filter(year == "2017",
         species == "DITE", 
         unittype!="IP") %>% 
  group_by(unittype, section) %>%
  summarize(counts = sum(entity)) %>% 
  group_by(section) %>% 
  mutate(proportion = round(((counts/sum(counts))*100), digits = 2))

# table

kable(dite_2017) %>% 
  kable_styling()


# Get the counts:
channel_section <- mack_raw %>%
  filter(year == "2017",
         species == "DITE", 
         unittype!="IP") %>% 
  group_by(unittype, section) %>%
  summarize(counts = sum(entity)) %>% 
  pivot_wider(names_from = unittype, values_from = counts) %>% 
  rename("Section" = section,
         "Cascades" = C,
         "Pool" = P,
         "Side-channel" = SC)

channel_section$Section <- gsub("CC", "Clear cut", channel_section$Section)
channel_section$Section <- gsub("OG", "Old growth", channel_section$Section)

channel_section_props <- channel_section %>% 
  adorn_percentages((denominator = "row")) %>% 
  adorn_pct_formatting(digits = 0) %>% 
  adorn_ns(position = "front")

kable(channel_section_props) %>% 
  kable_styling()
```

---

Part C:
```{r}
# chi-square test
chi_dite <- channel_section %>% 
  select(-Section)

dite_chi_test <- chisq.test(chi_dite)

dite_chi_test
```

- Report in text (in context of actual counts), referencing table from Part B

---

Part D:
```{r}
weight_section <- mack_raw %>% 
  filter(year == "2017",
         species == "DITE") %>% 
  group_by(section) %>% 
  summarize(median_weight = median(weight, na.rm = TRUE),
            mean_weight = round(mean(weight, na.rm = TRUE), digits = 2),
            sdev = round(sd(weight, na.rm = TRUE), digits = 2),
            count = sum(entity))

kable(weight_section) %>% 
  kable_styling()
```

---

Part E
```{r}
weight_channel <- mack_raw %>% 
  filter(year == "2017",
         species == "DITE",
         unittype != "IP") %>%
  group_by(unittype)

# Beeswarm
ggplot(data = weight_channel, aes(x = unittype, y = weight)) +
  geom_beeswarm()

# Jitter
ggplot(data = weight_channel, aes(x = unittype, y = weight)) +
  geom_jitter()

# Density (faceted)
ggplot(data = weight_channel, aes(x = weight, group = unittype, color = unittype)) +
  geom_density() +
  facet_wrap(~unittype)

# Histograms (faceted) 
ggplot(data = weight_channel, aes(x = weight)) +
  geom_histogram(aes(fill = unittype),
                 alpha = 0.5,
                 show.legend = FALSE,
                 bins = 15) +
  facet_wrap(~unittype, scales = "free")

# QQ plots (faceted)
ggplot(data = weight_channel, aes(sample = weight)) +
  geom_qq(aes(color = unittype),
                 alpha = 0.5,
                 show.legend = FALSE
          ) +
  facet_wrap(~unittype, scales = "free")
```

```{r}
weight_channel_summary <- weight_channel %>% 
  summarize(
    mean_weight = mean(weight, na.rm = TRUE),
    sd_weight = sd(weight, (na.rm = TRUE)),
    sample_size = n(),
    se_weight = sd((weight) / sqrt(n()), (na.rm = TRUE)),
    var_weight = var(weight, na.rm = TRUE)
  )

kable(weight_channel_summary) %>% 
  kable_styling()

# Importantly, variances are SOMEWHAT close (largest is < 4x greater than the smallest)
# But we can perform a Levene's Test for equal variances anyway: 

leveneTest(weight ~ unittype, data = weight_channel)
```

```{r}
# One-way ANOVA

weight_aov <- aov(weight ~ unittype, data = weight_channel)

summary(weight_aov)

# We retain the alternative hypothesis (mean weight for the 3 species are NOT the same). But are they all different from each other? Or just two? 

weight_lm <- lm(weight ~ unittype, data = weight_channel)
weight_aov_t3 <- Anova(weight_lm)

weight_aov_t3

## Anova Table (Type II tests)
## 
## Response: flipper_length_mm
##            Sum Sq  Df F value    Pr(>F)    
## species   21415.6   2  411.79 < 2.2e-16 ***
## Residuals  4212.6 162                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
# Notice that the F statistic value here (411.79) is almost exactly the same - the difference between these two is minimal. 
```

```{r}
TukeyHSD(weight_aov)
```

